version: "3.1"

services:
  
  cart-mysql:
    container_name: cart-mysql
    image: mysql:8
    volumes: 
    - ./mysql/data/:/var/lib/mysql
    - ./mysql/auth-plugin.cnf:/etc/mysql/conf.d/auth-plugin.cnf
    environment: 
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=app
    - MYSQL_PASSWORD=secret
    ports:
    - "8081:3306"
  
  cart:
    container_name: cart-nginx
    image: nginx:latest
    volumes:
    - ../:/cart
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
    - "81:80"
  
  cart-php:
    container_name: cart-php
    build: php-fpm
    working_dir: /cart
    volumes: 
    - ../:/cart
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

  cart-node:
    container_name: cart-node
    build: node
    working_dir: /cart-frontend
    volumes:
    - ../cart-frontend/:/cart-frontend
    - ../cart-frontend/node_modules/:/node_modules
    ports: 
    - "3000:3000"
    command: npm start

networks:
  dockerPrivate:
    driver: "bridge"

volumes:
  data: